-- VIEWS -> BUSCAR PELOS CLIENTES CADASTRADO E SUAS RESPECTIVAS COMPRAS COMO TAMBEM DATA E HORA
-- CRIANDO A VIEW
CREATE VIEW VW_HISTORICO_COMPRA AS 
	SELECT
	NOME_USUARIO AS 'CLIENTES',
	NOME_PRODUTO AS 'PRODUTO',
	DATA_VENDA AS 'DATA DA VENDA',
    VALOR_ITEM_PRODUTO AS 'VALOR POR ITEM',
    VALOR_DESCONTO_VENDA AS 'VALOR DE DESCONTO'
	FROM PRODUTOS
	INNER JOIN VENDAS_PRODUTOS
	ON PRODUTOS.ID = VENDAS_PRODUTOS.ID_PRODUTO
	INNER JOIN VENDAS
	ON VENDAS.ID = VENDAS_PRODUTOS.ID_VENDA
	INNER JOIN USUARIOS
	ON USUARIOS.ID = VENDAS.ID_USUARIO;
    

-- BUSCANDO INFORMAÇÕES DA VIEW
SELECT * FROM VW_HISTORICO_COMPRA;

-- BUSCAR CLIENTES QUE FAZEM ANIVERSARIO NO MES ATUAL 

CREATE VIEW VW_USUARIOS_ANIVERSARIOS AS
	SELECT
		NOME_USUARIO AS 'CLIENTE',
		month(DATA_NASC_USUARIO) AS 'MES DE NASCIMENTO'
	FROM USUARIOS
    INNER JOIN INFORMACOES
    ON USUARIOS.ID = INFORMACOES.ID_USUARIO
	WHERE month(DATA_NASC_USUARIO) = month(curdate());
    
SELECT * FROM VW_USUARIOS_ANIVERSARIOS;

-- VIEW - CLIENTES QUE MAIS GASTARAM NA LOJA

CREATE VIEW VW_USUARIO_FIEL AS 
	SELECT
		NOME_USUARIO AS 'CLIENTE',
        COUNT(VENDAS.ID_USUARIO) AS 'TOTAL DE COMPRAS',
        SUM(ROUND(VENDAS.VALOR_TOTAL_VENDA,2)) AS 'VALOR TOTAL'
        FROM USUARIOS
        INNER JOIN VENDAS
        ON USUARIOS.ID = VENDAS.ID_USUARIO GROUP BY NOME_USUARIO;
        
SELECT * FROM VW_USUARIO_FIEL;