
-- PROCEDURE PARA DAR BAIXA NA QUANTIDADE DE ESTOQUE SEMPRE QUANDO HÁ VENDA
DELIMITER $$
CREATE PROCEDURE SP_PRODUTO_BAIXAESTOQUE(IN NCODIGO INT, IN NQUANTIDADE INT)
BEGIN
	
	UPDATE PRODUTOS
	SET QUANTIDADE_PRODUTO = QUANTIDADE_PRODUTO - NQUANTIDADE
	WHERE ID = NCODIGO;
    
END $$
DELIMITER ;

CALL SP_PRODUTO_BAIXAESTOQUE(1,5);
SELECT * FROM PRODUTOS WHERE ID = 1;
