-- PROCEDURE PARA REGISTRAR ALTERAÇÃO DE VALOR DOS PRODUTOS
DELIMITER $$
CREATE PROCEDURE SP_ATUALIZAR_ITEM(
    IN PRODUTOID INT,
    IN PRECO_PRODUTO_ATUALIZADO FLOAT,
    IN DATA_PRODUTO_ATUALIZADO DATE
)
BEGIN
	IF((SELECT PRECO_PRODUTO FROM PRODUTOS WHERE ID = PRODUTOID)) THEN
		CREATE TABLE IF NOT EXISTS ATUALIZAR_PRODUTOS(
			ID INT AUTO_INCREMENT PRIMARY KEY,
            ID_PRODUTO INT,
            ATUALIZAR_PRECO FLOAT,
            DATA_PRODUTO_ATUALIZADO DATE,
            FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
        );
        INSERT INTO ATUALIZAR_PRODUTOS (ID, ID_PRODUTO, ATUALIZAR_PRECO, DATA_PRODUTO_ATUALIZADO)
        VALUES
        (NULL, PRODUTOID, PRECO_PRODUTO_ATUALIZADO, DATA_PRODUTO_ATUALIZADO);
		UPDATE PRODUTOS SET PRECO_PRODUTO = PRECO_PRODUTO_ATUALIZADO WHERE ID = PRODUTOID;
    END IF;
END $$

CALL SP_ATUALIZAR_ITEM(3,20, curdate());
select * from atualizar_produtos;
SELECT ID, PRECO_PRODUTO FROM PRODUTOS;


DELIMITER $$
CREATE PROCEDURE SP_ITEN_CARRINHO (
	IN PRODUTOID INT,
    IN QTD INT,
    IN PRECO DECIMAL(10,2)
)
BEGIN
	IF((SELECT QUANTIDADE_PRODUTO FROM PRODUTOS WHERE ID = PRODUTOID) >= QTD) THEN
		CREATE TABLE IF NOT EXISTS TEMP_CARRINHO (
			IDCARRINHO INT NOT NULL AUTO_INCREMENT,
			PRODID INT,
			QUANTIDADE INT,
			PRECO DECIMAL(10,2),
			PRIMARY KEY (IDCARRINHO)
		);
        INSERT INTO TEMP_CARRINHO (PRODID, QUANTIDADE, PRECO)
        VALUES
            (PRODUTOID, QTD, PRECO);
         SET @CARRINHO_COUNT = (SELECT COUNT(QUANTIDADE_PRODUTO) FROM PRODUTOS);
         SELECT "PRODUTO ADICIONADO COM SUCESSO" AS ALERTA;
         UPDATE PRODUTOS SET QUANTIDADE_PRODUTO = QUANTIDADE_PRODUTO - QTD WHERE ID = PRODUTOID;
    ELSE
        SELECT "SALDO DE ESTOQUE INSUFICIENTE NO MOMENTO" AS ALERTA;
    END IF;
END $$

CALL SP_ITEN_CARRINHO(1,2,(SELECT PRECO_PRODUTO FROM PRODUTOS WHERE ID = 1));
SELECT * FROM TEMP_CARRINHO;

SELECT ID, NOME_PRODUTO, QUANTIDADE_PRODUTO FROM PRODUTOS;

