-- SQL
-- 1- EXIBIR TODOS OS DADOS DA TABELA CLIENTES
SELECT * FROM ENDERECOS;

-- 1.1- INSERIR CLIENTE NO SISTEMA
INSERT INTO USUARIOS(ID, NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, IS_ADMIN)
VALUES
(NULL, 'JORGE COUTINHO', 'JORJAO@GMAIL.COM', 'A2223A4', 0);

INSERT INTO CLIENTES (ID, ID_USUARIO, DATA_NASC_CLIENTE, CPF_CLIENTE, FONE1_CLIENTE, FONE2_CLIENTE)
VALUES
(NULL, '6', '1991-12-28', '987-710-221-30', '(12)98921-1890', NULL);

INSERT INTO ENDERECOS (ID, ID_CLIENTE, ENDERECO_CLIENTE, BAIRRO_CLIENTE, NUMERO_CLIENTE, CIDADE_CLIENTE, ESTADO_CLIENTE)
VALUES
(NULL, '6', 'RUA ALFREDO TEXEIRA MACHADO', 'VILA REGINA CELIA', '232', 'CRUZEIRO', 'SÃO PAULO');


--  2- ATUALIZAR DADOS CADASTRADOS -> ATUALIZAR TROCA DE ENDEREÇO
UPDATE ENDERECOS 
SET ENDERECO_CLIENTE = 'RUA SETE DE SETEMBRO', BAIRRO_CLIENTE = 'CENTRO', NUMERO_CLIENTE = '727'
WHERE ID_CLIENTE = '6';


-- 3- REMOVER REGISTRO COM ID = 5 DA TABELA CLIENTES
DELETE FROM CLIENTES
WHERE ID = 5;

-- 4- EXIBIR TODOS OS CLIENTES COM AS DATAS DE COMPRA NO SISTEMA
SELECT 
	NOME_CLIENTE AS 'CLIENTE',
	DATA_VENDA AS 'DATA DA COMPRA'
FROM CLIENTES
INNER JOIN VENDAS
ON CLIENTES.ID = VENDAS.ID_CLIENTE;


-- VIEWS -> BUSCAR POR UM CLIENTE CADASTRADO E SUAS RESPECTIVAS COMPRAS
-- CRIANDO A VIEW
CREATE VIEW HISTORICO_COMPRA AS 
	SELECT 
		NOME_CLIENTE AS 'CLIENTE',
		DATA_VENDA AS 'DATA DA COMPRA',
		NOME_PRODUTO AS 'PRODUTO'
	FROM CLIENTES
	INNER JOIN VENDAS
	ON CLIENTES.ID = VENDAS.ID_CLIENTE
	INNER JOIN VENDAS_PRODUTOS
	ON VENDAS.ID = VENDAS_PRODUTOS.ID_VENDA
	INNER JOIN PRODUTOS
	ON VENDAS_PRODUTOS.ID_PRODUTO = PRODUTOS.ID;
    
-- BUSCANDO INFORMAÇÕES DA VIEW
SELECT * FROM HISTORICO_COMPRA;
SELECT * FROM VENDAS_PRODUTOS;

-- BUSCAR CLIENTES QUE FAZEM ANIVERSARIO NO MES ATUAL 

CREATE VIEW CLIENTES_ANIVERSARIOS AS
	SELECT
		NOME_CLIENTE AS 'CLIENTE',
		month(DATA_NASC_CLIENTE) AS 'MES DE NASCIMENTO'
	FROM CLIENTES
	WHERE month(DATA_NASC_CLIENTE) = month(curdate());
    
SELECT * FROM CLIENTES_ANIVERSARIOS;



-- CRIAR UMA PROCEDURES QUE RETORNAM A IDADE DOS CLIENTES
-- DELIMITADOR FINAL
DELIMITER $$
CREATE PROCEDURE IDADE(IN IDCLIENTE INT, OUT IDADE INT, OUT RES VARCHAR(20))
BEGIN
	
    DECLARE DT DATETIME;
    
    SET DT = (SELECT DATA_NASC_CLIENTE FROM CLIENTES WHERE ID = IDCLIENTE);
    
    SET IDADE = YEAR(NOW()) - YEAR(DT);
    
    IF(IDADE >= 32)THEN
		SET RES = TRUE;
	ELSE
		SET RES = FALSE;
	END IF;
    
    
END $$
DELIMITER ;
-- DEMILITADOR PADRÃO

-- CHAMAR A PROCEDURE
CALL IDADE(1, @IDADE_CLIENTE , @RES);
SELECT @IDADE_CLIENTE AS 'IDADE DO CLIENTE', @RES AS 'MAIORIDADE';







