-- CRIAR BANCO DE DADOS "CHECKPOINTGAMER_DH"
CREATE DATABASE CHECKPOINTGAMER_DH;
-- USAR BANCO DE DADOS
USE CHECKPOINTGAMER_DH;

-- CRIAR TABELAS
CREATE TABLE USUARIOS(
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    NOME_USUARIO VARCHAR(50) NOT NULL,
    EMAIL_USUARIO VARCHAR(50) NOT NULL,
    SENHA_USUARIO VARCHAR(50) NOT NULL,
    IS_ADMIN BOOLEAN NOT NULL
);


CREATE TABLE CLIENTES(
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    DATA_NASC_CLIENTE DATE NOT NULL,
    CPF_CLIENTE VARCHAR(50) NOT NULL,
    FONE1_CLIENTE VARCHAR(50) NOT NULL,
    FONE2_CLIENTE VARCHAR(50),
    
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);


CREATE TABLE ENDERECOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
	ENDERECO_CLIENTE VARCHAR(50) NOT NULL,
    BAIRRO_CLIENTE VARCHAR(50) NOT NULL,
    NUMERO_CLIENTE INT(6) NOT NULL,
    CIDADE_CLIENTE VARCHAR(50) NOT NULL,
    ESTADO_CLIENTE VARCHAR(50) NOT NULL,
    
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID)
);


CREATE TABLE FORNECEDORES (
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
	NOME_FORNECEDOR VARCHAR(50) NOT NULL,
    FONE1_FORNECEDOR VARCHAR(50) NOT NULL,
    FONE2_FORNECEDOR VARCHAR(50),
    EMAIL_FORNECEDOR VARCHAR(50) NOT NULL,
    SITE_FORNECEDOR VARCHAR(100),
    INSTAGRAM_FORNECEDOR VARCHAR(100)
);

CREATE TABLE CATEGORIAS(
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUTOS (
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    ID_FORNECEDOR INT NOT NULL,
    NOME_PRODUTO VARCHAR(50) NOT NULL,
    QUANTIDADE_PRODUTO INT NOT NULL,
    CUSTO_PRODUTO FLOAT NOT NULL,
    PRECO_PRODUTO FLOAT NOT NULL,
    PESO_PRODUTO FLOAT,
    ALTURA_PRODUTO FLOAT,
    LARGURA_PRODUTO FLOAT,
    COMPRIMENTO_PRODUTO FLOAT,
    
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID)
);

CREATE TABLE PRODUTOS_CATEGORIAS (
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID)
);

CREATE TABLE IMAGENS (
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    NOME_IMAGEM VARCHAR(50) NOT NULL,
    PASTA_IMAGEM VARCHAR(50) NOT NULL,
    
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
);

CREATE TABLE VENDAS (
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT(6) NOT NULL,
    DATA_VENDA DATETIME NOT NULL,
    VALOR_TOTAL_VENDA FLOAT NOT NULL,
    VALOR_DESCONTO_VENDA FLOAT NOT NULL,
    VALOR_FRETE_VENDA FLOAT NOT NULL,
    OBSERVACAO_VENDA VARCHAR(200),
    
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID)
);

CREATE TABLE VENDAS_PRODUTOS (
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    ID_VENDA INT NOT NULL,
    
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID),
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID)
);

CREATE TABLE CARTOES (
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    TITULAR_CARTAO VARCHAR(50) NOT NULL,
    NUMERO_CARTAO BIGINT(16) NOT NULL,
    VENCIMENTO_CARTAO DATE NOT NULL,
    CODIGO_CARTAO INT NOT NULL,
    BANDEIRA VARCHAR(50) NOT NULL
);

CREATE TABLE VENDAS_CARTOES (
	ID INT(6) AUTO_INCREMENT PRIMARY KEY,
    ID_VENDA INT(6) NOT NULL,
    ID_CARTAO INT(6) NOT NULL,
    
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID),
    FOREIGN KEY (ID_CARTAO) REFERENCES CARTOES(ID)
);
